config/routes.rb
Igni::Application.routes.draw do
  resources :days

  resources :months

  resources :weeks

  resources :plans

  resources :template_tasks

  resources :plan_tasks

  resources :tasks
  
  resources :periodes do  
  	collection do  
   	 post :sort     
  end
  end  
  
  resources :topics  
  

end

app/models/week.rb
class Week < Periode
	
	has_many :days
  	belongs_to :month
  	
  def periode_names
    self.days.map { |day| day.id }
  end  
  	
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  # GET /weeks
  # GET /weeks.xml
  def index
    @weeks = Week.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @weeks }
    end
  end

  # GET /weeks/1
  # GET /weeks/1.xml
  def show
    @week = Week.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @week }
    end
  end

  # GET /weeks/new
  # GET /weeks/new.xml
  def new
    @week = Week.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @week }
    end
  end

  # GET /weeks/1/edit
  def edit
    @week = Week.find(params[:id])
  end

  # POST /weeks
  # POST /weeks.xml
  def create
    @week = Week.new(params[:week])

    respond_to do |format|
      if @week.save
        format.html { redirect_to(@week, :notice => 'Week was successfully created.') }
        format.xml  { render :xml => @week, :status => :created, :location => @week }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @week.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /weeks/1
  # PUT /weeks/1.xml
  def update
    @week = Week.find(params[:id])

    respond_to do |format|
      if @week.update_attributes(params[:week])
        format.html { redirect_to(@week, :notice => 'Week was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @week.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /weeks/1
  # DELETE /weeks/1.xml
  def destroy
    @week = Week.find(params[:id])
    @week.destroy

    respond_to do |format|
      format.html { redirect_to(weeks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/weeks/_form.html.erb
<%= form_for(@week) do |f| %>
  <% if @week.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@week.errors.count, "error") %> prohibited this week from being saved:</h2>

      <ul>
      <% @week.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br />
    <%= f.date_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :plan_id %><br />
    <%= f.text_field :plan_id %>
  </div>
  <div class="field">
    <%= f.label :week_id %><br />
    <%= f.text_field :week_id %>
  </div>
  <div class="field">
    <%= f.label :month_id %><br />
    <%= f.text_field :month_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weeks/edit.html.erb
<h1>Editing week</h1>

<%= render 'form' %>

<%= link_to 'Show', @week %> |
<%= link_to 'Back', weeks_path %>

app/views/weeks/index.html.erb
<h1>Listing weeks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Startdate</th>
    <th>Plan</th>
    <th>Week</th>
    <th>Month</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @weeks.each do |week| %>
  <tr>
    <td><%= week.name %></td>
    <td><%= week.type %></td>
    <td><%= week.startdate %></td>
    <td><%= week.plan_id %></td>
    <td><%= week.week_id %></td>
    <td><%= week.month_id %></td>
    <td><%= link_to 'Show', week %></td>
    <td><%= link_to 'Edit', edit_week_path(week) %></td>
    <td><%= link_to 'Destroy', week, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Week', new_week_path %>

app/views/weeks/new.html.erb
<h1>New week</h1>

<%= render 'form' %>

<%= link_to 'Back', weeks_path %>

app/views/weeks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @week.name %>
</p>

<p>
  <b>Type:</b>
  <%= @week.type %>
</p>

<p>
  <b>Startdate:</b>
  <%= @week.startdate %>
</p>

<p>
  <b>Plan:</b>
  <%= @week.plan_id %>
</p>

<p>
  <b>Week:</b>
  <%= @week.week_id %>
</p>

<p>
  <b>Month:</b>
  <%= @week.month_id %>
</p>


<%= link_to 'Edit', edit_week_path(@week) %> |
<%= link_to 'Back', weeks_path %>