config/routes.rb
Igni::Application.routes.draw do
  resources :days

  resources :months

  resources :weeks

  resources :plans

  resources :template_tasks

  resources :plan_tasks

  resources :tasks
  
  resources :periodes do  
  	collection do  
   	 post :sort     
  end
  end  
  
  resources :topics  
  

end

app/models/day.rb
class Day < Periode
	 belongs_to :week
	 
	 def periode_names
	 	[self.id]
	 end
	 
	 
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  # GET /days
  # GET /days.xml
  def index
    @days = Day.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @days }
    end
  end

  # GET /days/1
  # GET /days/1.xml
  def show
    @day = Day.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @day }
    end
  end

  # GET /days/new
  # GET /days/new.xml
  def new
    @day = Day.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @day }
    end
  end

  # GET /days/1/edit
  def edit
    @day = Day.find(params[:id])
  end

  # POST /days
  # POST /days.xml
  def create
    @day = Day.new(params[:day])

    respond_to do |format|
      if @day.save
        format.html { redirect_to(@day, :notice => 'Day was successfully created.') }
        format.xml  { render :xml => @day, :status => :created, :location => @day }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @day.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /days/1
  # PUT /days/1.xml
  def update
    @day = Day.find(params[:id])

    respond_to do |format|
      if @day.update_attributes(params[:day])
        format.html { redirect_to(@day, :notice => 'Day was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @day.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.xml
  def destroy
    @day = Day.find(params[:id])
    @day.destroy

    respond_to do |format|
      format.html { redirect_to(days_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/_form.html.erb
<%= form_for(@day) do |f| %>
  <% if @day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@day.errors.count, "error") %> prohibited this day from being saved:</h2>

      <ul>
      <% @day.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br />
    <%= f.date_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :plan_id %><br />
    <%= f.text_field :plan_id %>
  </div>
  <div class="field">
    <%= f.label :week_id %><br />
    <%= f.text_field :week_id %>
  </div>
  <div class="field">
    <%= f.label :month_id %><br />
    <%= f.text_field :month_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/days/edit.html.erb
<h1>Editing day</h1>

<%= render 'form' %>

<%= link_to 'Show', @day %> |
<%= link_to 'Back', days_path %>

app/views/days/index.html.erb
<h1>Listing days</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Startdate</th>
    <th>Plan</th>
    <th>Week</th>
    <th>Month</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @days.each do |day| %>
  <tr>
    <td><%= day.name %></td>
    <td><%= day.type %></td>
    <td><%= day.startdate %></td>
    <td><%= day.plan_id %></td>
    <td><%= day.week_id %></td>
    <td><%= day.month_id %></td>
    <td><%= link_to 'Show', day %></td>
    <td><%= link_to 'Edit', edit_day_path(day) %></td>
    <td><%= link_to 'Destroy', day, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Day', new_day_path %>

app/views/days/new.html.erb
<h1>New day</h1>

<%= render 'form' %>

<%= link_to 'Back', days_path %>

app/views/days/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @day.name %>
</p>

<p>
  <b>Type:</b>
  <%= @day.type %>
</p>

<p>
  <b>Startdate:</b>
  <%= @day.startdate %>
</p>

<p>
  <b>Plan:</b>
  <%= @day.plan_id %>
</p>

<p>
  <b>Week:</b>
  <%= @day.week_id %>
</p>

<p>
  <b>Month:</b>
  <%= @day.month_id %>
</p>


<%= link_to 'Edit', edit_day_path(@day) %> |
<%= link_to 'Back', days_path %>