config/routes.rb
Igni::Application.routes.draw do
  resources :days

  resources :months

  resources :weeks

  resources :plans

  resources :template_tasks

  resources :plan_tasks

  resources :tasks
  
  resources :periodes do  
  	collection do  
   	 post :sort     
  end
  end  
  
  resources :topics  
  

end

app/models/plan.rb
class Plan < Periode
	 has_many :periodes

   
  def periode_names
    periodes = []
    self.periodes.each do |periode|
      periodes << periode.id
      periodes += periode.periode_names
    end
    periodes
  end


  def all_plan_tasks_names
  	periodeIds = self.periode_names
  	tasks = []	
  	periodeIds.each do |periodeId|
  		tasks += Periode.find(periodeId).tasks.map { |task| task.name }
  	end
  	tasks  	
 end
 
  	
  def addInitialPeriodes
    
    @month = Month.new(:name => "Month1")
    @week = Week.create(:name => "Week1")
    @day1 = Day.create(:name => "Day1")
    @day2 = Day.create(:name => "Day2")
    
    @week.days << @day1
    @week.days << @day2
    @month.weeks << @week
    
    self.periodes << @month    
  end


end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
require 'plan_drawer'
  # GET /plans
  # GET /plans.xml
  def index
    @plans = Plan.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @plans }
    end
  end

  # GET /plans/1
  # GET /plans/1.xml
  def show
    @plan = Plan.find(params[:id])
	  @templateTasks = TemplateTask.all
	 
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @plan }
      format.pdf  do       
        send_data PlanDrawer.draw(@plan), :filename => "plan.pdf",:type => "application/pdf", :disposition => 'inline'
      end 
    end
  end

  # GET /plans/new
  # GET /plans/new.xml
  def new
    @plan = Plan.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @plan }
    end
  end

  # GET /plans/1/edit
  def edit
    @plan = Plan.find(params[:id])
  end

  # POST /plans
  # POST /plans.xml
  def create
    @plan = Plan.new(params[:plan])
    @plan.addInitialPeriodes
    
    respond_to do |format|
      if @plan.save
        format.html { redirect_to(@plan, :notice => 'Plan was successfully created.') }
        format.xml  { render :xml => @plan, :status => :created, :location => @plan }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @plan.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /plans/1
  # PUT /plans/1.xml
  def update
    @plan = Plan.find(params[:id])

    respond_to do |format|
      if @plan.update_attributes(params[:plan])
        format.html { redirect_to(@plan, :notice => 'Plan was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @plan.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.xml
  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy

    respond_to do |format|
      format.html { redirect_to(plans_url) }
      format.xml  { head :ok }
    end
  end
  
  
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br />
    <%= f.date_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :plan_id %><br />
    <%= f.text_field :plan_id %>
  </div>
  <div class="field">
    <%= f.label :week_id %><br />
    <%= f.text_field :week_id %>
  </div>
  <div class="field">
    <%= f.label :month_id %><br />
    <%= f.text_field :month_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<h1>Listing plans</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Startdate</th>
    <th>Plan</th>
    <th>Week</th>
    <th>Month</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @plans.each do |plan| %>
  <tr>
    <td><%= plan.name %></td>
    <td><%= plan.type %></td>
    <td><%= plan.startdate %></td>
    <td><%= plan.plan_id %></td>
    <td><%= plan.week_id %></td>
    <td><%= plan.month_id %></td>
    <td><%= link_to 'Show', plan %></td>
    <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
    <td><%= link_to 'Destroy', plan, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Plan', new_plan_path %>

app/views/plans/new.html.erb
<h1>New plan</h1>

<%= render 'form' %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p>
  <b>Name:</b>
  <%= @plan.name %>
</p>
<p>
  <b>Type:</b>
  <%= @plan.type %>
</p>
<p>
  <b>Startdate:</b>
  <%= @plan.startdate %>
</p>



<div id="pool">
	<%= render :partial => @templateTasks %>
</div>



<div id="plan">
	<% @plan.periodes.each do |month| %>
		<% month.weeks.each do |week | %>
			<% week.days.each do |day| %>
				<!-- Show Tasks for each Day-->
				<div id="<%= day.id %>" > 
					Tag: <%= day.name %>
					<%= render :partial => day.tasks %>
				</div>
			<% end %>
						
			<!-- Show Tasks for each Week-->
			<div id="<%= week.id %>" >
				Woche
				<%= render :partial => week.tasks  %>	
			</div>
		<% end %>
		
		<!-- Show Tasks for each Month-->
		<div id="<%= month.id %>" >
			Monat
			<%= render :partial => month.tasks %>	
		</div>
	<% end %>
</div>		



<!-- Create all sortables-->
<% periodeIds = @plan.periode_names%>
<% periodeIds << 'pool' %>
<% periodeIds.each do |periodeId| %>
	<%= sortable_element(periodeId.to_s,
		:containment => periodeIds,
		:dropOnEmpty => true,
		:url => { :action => 'sort' ,:controller => 'periodes', :periodeId => periodeId, :planId => @plan.id},
		:complete => visual_effect(:shake,  periodeId.to_s))%>	
<% end %>


<%= link_to 'PDF drucken', plan_path(@plan, :format => :pdf) %>